In [22]:
#!/usr/bin/env python
""" 
"""
__author__ = 'Adam Duster'
__copyright__ = ''
__credits__ = ['Adam Duster']
__license__ = 'CC-BY-SA'
__version__ = '0.1'
__email__ = 'adam.duster@ucdenver.edu'
__status__ = 'Development'

import argparse
def get_args(args=None):
    """ This is written as a default funtion to put at beginning of all Python
    scripts which require command line arguments. This uses the argparse module
    which must be declared in the main program to ensure that the object is able
    to be used by the caller
    --Adam Duster 21 June 2017
    """
    parser = argparse.ArgumentParser(description='see header of python script')
    parser.add_argument(
        '-i',
        '--if_paths',
        help='The first and second files in order',
        nargs=2,
        required=True)
    parser.add_argument(
        '-v',
        '--verbose',
        help='Controls the level of output, use multipe v for more output',
        required=False,
        action='count',
        default=0)
    parser.add_argument(
        '-s',
        '--step',
        help='The change in coordinates between the two files',
        required=False,
        default=1e-6
    )
    parser.add_argument(
        '-d',
        '--debug',
        help='Enter debug mode',
        required=False,
        action='store_true',
        default=False)
    return parser.parse_args(args)

## Vars
arg_vals = None
args = get_args(['-i', 'step1_bf.h5', 'step2_bf.h5'])



In [26]:
# Calculate the numerical gradient
import h5py as h5
import numpy as np

key = 'h_rad_cartesian_gradient'
#key = 'h_radial_sym_funcs'
check = False
check = True
print(args.if_paths[0])
print(args.if_paths[1])
k = 0
with h5.File(args.if_paths[0], 'r') as ffi, h5.File(args.if_paths[1], 'r') as nfi:
    if check:
        for i in range(nfi[key].shape[0]):
            for j in range(nfi[key].shape[1]):
                if not np.isclose(nfi[key][i,j].any(), ffi[key][i, j].any(), 1e-7):
                    print(i, j)
                    k += 1
    print(nfi[key][0,:5])
    print(ffi[key][0,:5])
    print(list(nfi.keys()))
    delta_symfuncs = (nfi[key][:] - ffi[key][:] ) / args.step
print(k)

step1_bf.h5
step2_bf.h5
[[ 2.61709938e-04 -3.25162909e-05 -1.24023267e-04]
 [ 9.31795044e-01 -1.15511964e-01 -4.41535858e-01]
 [ 6.17195450e-01  1.37647972e-02 -2.48853248e-01]
 [-2.91376599e+00  5.73273592e-01  2.14562578e+00]
 [-1.18213050e+00  1.10503988e-01  1.37148343e+00]]
[[ 2.61709938e-04 -3.25162909e-05 -1.24023267e-04]
 [ 9.31795044e-01 -1.15511964e-01 -4.41535858e-01]
 [ 6.17195450e-01  1.37647972e-02 -2.48853248e-01]
 [-2.91376599e+00  5.73273592e-01  2.14562578e+00]
 [-1.18213050e+00  1.10503988e-01  1.37148343e+00]]
['h_angular_sym_funcs', 'h_basis_to_molecule', 'h_rad_cartesian_gradient', 'h_radial_sym_funcs', 'molecule_to_basis_inds', 'o_angular_sym_funcs', 'o_basis_to_molecule', 'o_rad_cartesian_gradient', 'o_radial_sym_funcs']
0


In [12]:
key = 'cartesian_coords'
with h5.File('step1_coords.h5', 'r') as ffi, h5.File('step2_coords.h5', 'r') as nfi:
    print(nfi[key][0:2,:5])
    print(ffi[key][0:2,:5])

[[[-1.502069 -0.191259  1.435027]
  [-0.600954 -0.596872  1.553818]
  [-2.006598 -0.422227  2.219947]
  [-1.744475 -0.382248 -1.309044]
  [-1.888841 -0.479553 -0.347524]]

 [[-1.502169 -0.191359  1.434927]
  [-0.601054 -0.596972  1.553718]
  [-2.006698 -0.422327  2.219847]
  [-1.744575 -0.382348 -1.309144]
  [-1.888941 -0.479653 -0.347624]]]
[[[-1.502169 -0.191359  1.434927]
  [-0.601054 -0.596972  1.553718]
  [-2.006698 -0.422327  2.219847]
  [-1.744575 -0.382348 -1.309144]
  [-1.888941 -0.479653 -0.347624]]

 [[-1.502169 -0.191359  1.434927]
  [-0.601054 -0.596972  1.553718]
  [-2.006698 -0.422327  2.219847]
  [-1.744575 -0.382348 -1.309144]
  [-1.888941 -0.479653 -0.347624]]]
