In [1]:
#!/usr/bin/env python
""" 
"""
__author__ = 'Adam Duster'
__copyright__ = ''
__credits__ = ['Adam Duster']
__license__ = 'CC-BY-SA'
__version__ = '0.1'
__email__ = 'adam.duster@ucdenver.edu'
__status__ = 'Development'

import argparse
def get_args(args=None):
    """ This is written as a default funtion to put at beginning of all Python
    scripts which require command line arguments. This uses the argparse module
    which must be declared in the main program to ensure that the object is able
    to be used by the caller
    --Adam Duster 21 June 2017
    """
    parser = argparse.ArgumentParser(description='see header of python script')
    parser.add_argument(
        '-i',
        '--if_paths',
        help='The first and second files in order',
        nargs=2,
        required=True)
    parser.add_argument(
        '-v',
        '--verbose',
        help='Controls the level of output, use multipe v for more output',
        required=False,
        action='count',
        default=0)
    parser.add_argument(
        '-s',
        '--step',
        help='The change in coordinates between the two files',
        required=False,
        default=1e-6,
        type=float
    )
    parser.add_argument(
        '-d',
        '--debug',
        help='Enter debug mode',
        required=False,
        action='store_true',
        default=False)
    return parser.parse_args(args)

## Vars
arg_vals = None
args = get_args(['-i', 'step1_bf.h5', 'step2_bf.h5', '-s', '1e-6'])



In [7]:
# Calculate the numerical gradient
import h5py as h5
import numpy as np

#key = 'o_rad_cartesian_gradient'
#key = 'h_radial_sym_funcs'
key = 'o_radial_sym_funcs'
ckey = 'o_rad_cartesian_gradient'
check = False
check = True
print(args.if_paths[0])
print(args.if_paths[1])
k = 0
with h5.File(args.if_paths[0], 'r') as ffi, h5.File(args.if_paths[1], 'r') as nfi:
    if check:
        for i in range(nfi[key].shape[0]):
            for j in range(nfi[key].shape[1]):
                if not np.isclose(nfi[key][i,j].any(), ffi[key][i, j].any(), 1e-5):
                    print(i, j)
                    k += 1
    print(key, 'shape: ', nfi[key].shape)
    print(nfi[key][0,:5])
    print(ffi[key][0,:5])
    print(list(nfi.keys()))
    delta_symfuncs = (nfi[key][0,:] - ffi[key][0,:] ) / args.step
    #calc = (nfi[ckey][0,:,0] + ffi[ckey][0,:,0])/2.
    print(ckey, 'shape: ', ffi[ckey].shape)
    calc = ffi[ckey][0,:,0:2,0]
    print(ffi[ckey][0,1,0])
    print(calc)
#print(delta_symfuncs)
#print(calc)

step1_bf.h5
step2_bf.h5
o_radial_sym_funcs shape:  (1, 48)
[0.44041157 0.84557164 0.3151581  0.10059809 0.03598231]
[0.44040811 0.84557348 0.31515974 0.1005987  0.03598253]
['h_angular_sym_funcs', 'h_basis_to_molecule', 'h_rad_cartesian_gradient', 'h_radial_sym_funcs', 'molecule_to_basis_inds', 'o_angular_sym_funcs', 'o_basis_to_molecule', 'o_rad_cartesian_gradient', 'o_radial_sym_funcs']
o_rad_cartesian_gradient shape:  (1, 48, 151, 3)
[1.86286294 0.         0.        ]
[[-3.47508979e+00  3.47508979e+00]
 [ 1.86286294e+00 -1.86286294e+00]
 [ 1.62611556e+00 -1.62611556e+00]
 [ 6.06737137e-01 -6.06737137e-01]
 [ 2.21934795e-01 -2.21934795e-01]
 [ 9.00110602e-02 -9.00110602e-02]
 [ 4.10009511e-02 -4.10009511e-02]
 [ 2.07312386e-02 -2.07312386e-02]
 [ 1.14523806e-02 -1.14523806e-02]
 [ 6.81113498e-03 -6.81113498e-03]
 [ 4.30742232e-03 -4.30742232e-03]
 [ 2.86747469e-03 -2.86747469e-03]
 [ 1.99303776e-03 -1.99303776e-03]
 [ 1.43679068e-03 -1.43679068e-03]
 [ 1.06856506e-03 -1.06856506e-03]

In [3]:
for i in range(delta_symfuncs.size):
    if delta_symfuncs[i] == 0 and calc[i] == 0:
        continue
    print(delta_symfuncs[i], calc[i], calc[i]-delta_symfuncs[i], (calc[i]-delta_symfuncs[i])/delta_symfuncs[i])

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [8]:
for i in range(delta_symfuncs.size):
    if delta_symfuncs[i].all() == 0 and calc[i].all() == 0:
        continue
    print(delta_symfuncs[i], calc[i], (calc[i]-delta_symfuncs[i])/delta_symfuncs[i])

3.4570693969726562 [-3.47508979  3.47508979] [-2.00521262  0.00521262]
-1.8477439880371094 [ 1.86286294 -1.86286294] [-2.00818239  0.00818239]
-1.6391277313232422 [ 1.62611556 -1.62611556] [-1.99206153 -0.00793847]
-0.6109476089477539 [ 0.60673714 -0.60673714] [-1.99310829 -0.00689171]
-0.22351741790771484 [ 0.2219348 -0.2219348] [-1.99291947 -0.00708053]
-0.08940696716308594 [ 0.09001106 -0.09001106] [-2.00675667  0.00675667]
-0.040978193283081055 [ 0.04100095 -0.04100095] [-2.00055536e+00  5.55363636e-04]
-0.020954757928848267 [ 0.02073124 -0.02073124] [-1.98933324 -0.01066676]
-0.011408701539039612 [ 0.01145238 -0.01145238] [-2.00382857  0.00382857]
-0.006868503987789154 [ 0.00681113 -0.00681113] [-1.99164753 -0.00835247]
-0.004249159246683121 [ 0.00430742 -0.00430742] [-2.01371167  0.01371167]
-0.002852175384759903 [ 0.00286747 -0.00286747] [-2.00536408  0.00536408]
-0.001979060471057892 [ 0.00199304 -0.00199304] [-2.00706259  0.00706259]
-0.0014260876923799515 [ 0.00143679 -0.0014

In [5]:
for i in range(delta_symfuncs.size):
    if delta_symfuncs[i] == 0 and calc[i] == 0:
        continue
    print(delta_symfuncs[i], calc[i], (calc[i]-delta_symfuncs[i])/delta_symfuncs[i])

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [48]:
# Calculate the numerical gradient
import h5py as h5
import numpy as np

#key = 'o_rad_cartesian_gradient'
#key = 'h_radial_sym_funcs'
key = 'cartesian_coords'
check = False
check = True
f1 = 'step1_coords.h5'
f2 = 'step2_coords.h5'
print(args.if_paths[0])
print(args.if_paths[1])
k = 0
with h5.File(f1, 'r') as ffi, h5.File(f2, 'r') as nfi:
    if check:
        assert(nfi[key].shape[0] == ffi[key].shape[0])
        assert(nfi[key].shape[1] == ffi[key].shape[1])
        print("Shape to check: ", nfi[key].shape)
        for i in range(nfi[key].shape[0]):
            for j in range(nfi[key].shape[1]):
                for l in range(3):
                    if not np.isclose(nfi[key][i, j, l].any(), ffi[key][i, j, l].any(), 1e-7):
                        print(i, j, l)
                        k += 1
    print(nfi[key][1,:5])
    print(ffi[key][1,:5])
    print(list(nfi.keys()))
    delta_symfuncs = (nfi[key][:] - ffi[key][:] ) / args.step
print(k)

step1_bf.h5
step2_bf.h5
Shape to check:  (1, 151, 3)
0 0 2


ValueError: Index (1) out of range (0-0)

In [59]:
key = 'cartesian_coords'
with h5.File('step1_coords.h5', 'r') as ffi, h5.File('step2_coords.h5', 'r') as nfi:
    print(nfi[key][0:2,:5])
    print(ffi[key][0:2,:5])

[[[-0.999999  0.        0.      ]
  [ 0.        0.        0.      ]
  [ 0.        0.        0.      ]
  [ 0.        0.        0.      ]
  [ 0.        0.        0.      ]]]
[[[-1.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]]
